<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="About.aspx.cs" Inherits="PersonalSite.About" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div>
        <h1>About me</h1>
        <p>I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand itI dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.</p>
        <p>I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand itI dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.I dont like asp net at the moment because i find it too dificult to work with and i dont have time and the will to understand it.</p>
    </div>
</asp:Content>
